### ISSUE TITLE
360° video metadata injection

### ISSUE THREAD

**Issue by duncanleo** [raboof/dualfisheye2equirectangular#4]
Hi,

I chanced upon an article describing how to inject 360 metadata into a video - it makes use of a couple of utilities maintained by Google - https://github.com/google/spatial-media

**Comment by raboof** [comment]
Interesting. What do you propose? To add a link to it in the README?

**Comment by duncanleo** [comment]
That sounds good. Would you like me to make a PR?

**Comment by raboof** [comment]
Please do!
